const { getDefaultConfig } = require('expo/metro-config');

const config = getDefaultConfig(__dirname);

// Override conditionNames to drop 'import' — using 'import' causes @babel/runtime/helpers/*
// to resolve to their ESM variants (esm/interopRequireDefault.js etc.) instead of the CJS
// variants. The module code generated by babel-preset-expo calls require() directly without
// _$$_IMPORT_DEFAULT wrapping, so it gets { default: fn } instead of the function itself,
// causing "TypeError: _interopRequireDefault is not a function" at runtime.
config.resolver.unstable_conditionNames = ['require', 'default'];

module.exports = config;
